---
title: "A Gender Inequalities Study "
author: "Anais HOAREAU, Sébastien MARCHAL, Rémi NAHON"
date: "`r format(Sys.time(), '%d %B %Y')`"
mail: "anais.hoareau@mines-ales.org, sebastien.marchal@mines-ales.org, remi.nahon@mines-ales.org"
linkedin: "rémi-nahon-609901160"
logo: "images/fem.jpg"
output:
  epuRate::epurate:
    toc: TRUE
    number_sections: FALSE
    code_folding: "hide"
---

# Titre du rapport

<br><br>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, tidy = TRUE, 
                      message = FALSE, fig.align = "center", eval = TRUE)
```


```{r import_libraries, echo = FALSE}
library(tidyverse)
library(rmarkdown)    
library(epuRate)      
library(dplyr)
library(ggplot2)
library(shiny)
library(plotly)
library(viridis)
library(gridExtra)
```


```{r data_load}
# Loading of the data
data <- read.csv("data/gender_inequality.csv")
# First visualization
arrange(data, desc(data$Gender.Inequality.Index..GII.))
tail(data, 20)
# Changement du type des colonnes pour en faciliter la manipulation
data$Gender.Inequality.Index..GII. <- as.numeric(as.character(data$Gender.Inequality.Index..GII.))
data$Maternal.Mortality.Ratio <- as.numeric(as.character(data$Maternal.Mortality.Ratio))
data$Adolescent.Birth.Rate <- as.numeric(as.character(data$Adolescent.Birth.Rate))
data$Percent.Representation.in.Parliament <- as.numeric(as.character(data$Percent.Representation.in.Parliament))
data$Population.with.Secondary.Education..Female. <- as.numeric(as.character(data$Population.with.Secondary.Education..Female.))
data$Population.with.Secondary.Education..Male. <- as.numeric(as.character(data$Population.with.Secondary.Education..Male.))
data$Labour.Force.Participation.Rate..Female. <- as.numeric(as.character(data$Labour.Force.Participation.Rate..Female.))
data$Labour.Force.Participation.Rate..Male. <- as.numeric(as.character(data$Labour.Force.Participation.Rate..Male.))
```

```{r lollipop}
g1 = data %>%
  filter(Gender.Inequality.Index..GII. != "..") %>% # Elimination of the countries without GII data
  filter(!is.na(GII.Rank)) %>% # Elimination of the world and continent datas
  arrange(desc(Gender.Inequality.Index..GII.)) %>% 
  mutate(Country=factor(Country, Country)) %>%
  tail(20)%>%
  ggplot( aes(x=Country, y=Gender.Inequality.Index..GII.) ) +
    geom_segment( aes(x = Country, 
                      xend = Country,
                      y = 0,
                      yend = Gender.Inequality.Index..GII.),
                  color = "grey") +
    geom_point(size=3, color="#7baeff") +
    coord_flip() +
    theme(panel.grid.minor.y = element_blank(),
          panel.grid.major.y = element_blank()) +
    xlab("") +
    ylab("GII") + 
    ggtitle("Gender Inequality Index \n Top 20 Countries")

g2 = data %>%
  filter(Gender.Inequality.Index..GII. != "..") %>% 
  filter(!is.na(GII.Rank)) %>% 
  arrange(desc(Gender.Inequality.Index..GII.)) %>%
  mutate(Country=factor(Country, Country)) %>%
  head(15)%>%
  ggplot( aes(x=Country, y=Gender.Inequality.Index..GII.) ) +
    geom_segment( aes(x = Country, 
                      xend = Country,
                      y = 0.55,
                      yend = Gender.Inequality.Index..GII.),
                  color = "grey") +
    geom_point(size=3, color="#d071ff") +
    coord_flip() +
    theme(panel.grid.minor.y = element_blank(),
          panel.grid.major.y = element_blank()) +
    xlab("") +
    ylab("GII")+
    ggtitle("Gender Inequality Index \n Bottom 20 Countries")

g3 = data %>%
  filter(Gender.Inequality.Index..GII. != "..") %>% 
  filter(is.na(GII.Rank)) %>%
  filter(Country != "World") %>% # Selection of continent datas
  arrange(desc(Gender.Inequality.Index..GII.)) %>%
  mutate(Country=factor(Country, Country)) %>%
  ggplot( aes(x=Country, y=Gender.Inequality.Index..GII.) ) +
    geom_segment( aes(x = Country, 
                      xend = Country,
                      y = 0,
                      yend = Gender.Inequality.Index..GII.),
                  color = "grey") +
    geom_point(size=3, color="#ffb57b") +
    coord_flip() +
    theme(panel.grid.minor.y = element_blank(),
          panel.grid.major.y = element_blank()) +
    xlab("") +
    ylab("Medium GII")+
    ggtitle("Gender Inequality Index \n Continent indexes") +
    geom_hline(yintercept=0.449, color="#7baeff", size=1) +
    annotate("text", x = 3.5 , y = 0.5, label = "World GII" , color="#7baeff", size=3 , angle=0, fontface="bold") +
    geom_hline(yintercept=0.016, color="#2ec212", size=1) +
    annotate("text", x = 3.5 , y = 0.08, label = "Lowest GII\nSlovenia", color="#2ec212", size=3 , angle=0, fontface="bold") +
    geom_hline(yintercept=0.744, color="#da7855", size=1) +
    annotate("text", x = 3.5 , y = 0.68
             , label = "Highest GII\nYemen" , color="#da7855", size=3 , angle=0, fontface="bold")
  


g1
g2
g3

```

```{r anais multichart}
# Basic ggplot
p <- data %>%
  mutate(myText=paste(Country)) %>%
  ggplot( aes(x= Population.with.Secondary.Education..Female., y=Population.with.Secondary.Education..Male., 
              color = Maternal.Mortality.Ratio, text=myText)) +
    geom_point() + 
    scale_color_viridis(option = "D") +
    theme(panel.grid.minor.y = element_blank(),
        panel.grid.major.y = element_blank(),
        #axis.text.x = element_blank(),
        #axis.text.y = element_blank(),
        axis.ticks = element_blank())

ggplotly(p, tooltip="text")

```

```{r}
p <- data %>%
  mutate(myText=paste(Country)) %>%
  ggplot( aes(x= Population.with.Secondary.Education..Female., y=Maternal.Mortality.Ratio , 
              color = Adolescent.Birth.Rate, text=myText)) +
    geom_point() + 
    scale_color_viridis(option = "D") +
    theme(
      panel.grid.minor.y = element_blank(),
      panel.grid.major.y = element_blank(),
      panel.grid.minor.x = element_blank(),
      axis.ticks = element_blank())

ggplotly(p, tooltip="text")

```

